# Generated by Django 3.0.8 on 2020-07-28 14:57

import app.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='', validators=[app.models.validate_image], verbose_name='Foto')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=30, verbose_name='Sobrenome')),
                ('cpf', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}\\-\\d{2}$', message="Formato esperado: '999.999.999-99'")], verbose_name='CPF')),
                ('rg', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^(\\d\\.?-?)+$')], verbose_name='RG')),
                ('telefone', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('\\(\\d{2}\\) \\d{5}-\\d{4}', message="Formato esperado: '(99) 99999-9999'")], verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='ClienteArquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_on', models.DateTimeField(auto_now_add=True)),
                ('original_pk', models.IntegerField()),
                ('foto', models.ImageField(upload_to='')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=30)),
                ('rg', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='EnderecoArquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_original', models.IntegerField()),
                ('original_pk', models.IntegerField()),
                ('tipo', models.CharField(max_length=10)),
                ('logradouro', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=2)),
                ('numero', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Principal', 'Principal'), ('Secundário', 'Secundário')], default='Principal', max_length=10, verbose_name='Tipo')),
                ('logradouro', models.CharField(max_length=30, verbose_name='Logradouro')),
                ('bairro', models.CharField(max_length=30, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=30, verbose_name='Cidade')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='SP', max_length=2, verbose_name='Estado')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='app.Cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Endereço',
                'unique_together': {('logradouro', 'bairro', 'cidade', 'estado', 'numero')},
            },
        ),
    ]
